//! Generates the byte-compat fixtures the iOS app's unit tests decode
//! (`apps/ios-key/NorthKeyTests/Fixtures/golden-vault.json`). The Swift vault crypto
//! (Argon2id KEK → SNTL unwrap → SVLT sync-blob decode → item envelopes) must reproduce these
//! bytes exactly — that is the interop guarantee between desktop and phone.
//!
//! Regenerate (rarely — only on a format change) with:
//!   cargo test -p sentinel-core --test ios_golden_vectors -- --ignored generate
//! then commit the JSON. Uses the PRODUCTION Argon2 profile on purpose: the fixture must match
//! what real escrowed blobs use (the Swift test takes ~1s on-device for the 64 MiB derivation).

use base64::Engine as _;
use sentinel_core::crypto::{Argon2Profile, Key32};
use sentinel_core::keyring::password::PasswordWrapper;
use sentinel_core::keyring::{KeyWrapper, VaultKey};
use sentinel_core::vault::model::{Item, Login};
use sentinel_core::vault::{encode_sync_blob, seal_item, VaultDocument};

#[test]
#[ignore = "writes the committed iOS fixture; run explicitly to regenerate"]
fn generate() {
    let b64 = |b: &[u8]| base64::engine::general_purpose::STANDARD.encode(b);
    let password = "morning-test-master-password";
    let vk = VaultKey::from_key(Key32::from_bytes([0x42; 32]));

    let wrapper = PasswordWrapper::with_profile(password, Argon2Profile::Production);
    let wrapped = tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(wrapper.wrap(&vk))
        .unwrap();

    let mut a = Item::new_login("GitHub", 1_750_000_000);
    a.id = uuid::Uuid::from_bytes([0xA1; 16]);
    a.login = Some(Login {
        username: Some("octocat".into()),
        password: Some("hunter2-golden".into()),
        totp: None,
    });
    let mut b = Item::new_login("Example Bank", 1_750_000_100);
    b.id = uuid::Uuid::from_bytes([0xB2; 16]);
    b.login = Some(Login {
        username: Some("jackson".into()),
        password: Some("s3cure-golden".into()),
        totp: None,
    });

    let envs = vec![seal_item(&vk, &a).unwrap(), seal_item(&vk, &b).unwrap()];
    let doc = VaultDocument::from_envelopes(&envs, vec![]);
    let version = 3u64;
    let blob = encode_sync_blob(&vk, &doc, version).unwrap();

    let fixture = serde_json::json!({
        "comment": "generated by crates/core/tests/ios_golden_vectors.rs — do not hand-edit",
        "password": password,
        "vault_key_b64": b64(vk.key().as_bytes()),
        "wrapped_key_b64": b64(&wrapped.bytes),
        "argon2": { "m_kib": 65536, "t": 3, "p": 4 },
        "vault_version": version,
        "vault_blob_b64": b64(&blob),
        "items": [
            { "id": a.id.to_string(), "title": "GitHub", "username": "octocat", "password": "hunter2-golden" },
            { "id": b.id.to_string(), "title": "Example Bank", "username": "jackson", "password": "s3cure-golden" },
        ],
    });
    let out = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../apps/ios-key/NorthKeyTests/Fixtures/golden-vault.json"
    );
    std::fs::create_dir_all(std::path::Path::new(out).parent().unwrap()).unwrap();
    std::fs::write(out, serde_json::to_string_pretty(&fixture).unwrap()).unwrap();
    println!("wrote {out}");
}
