// Byte-compatibility tests against the desktop's Rust crypto. The fixture
// (Fixtures/golden-vault.json) is generated by `crates/core/tests/ios_golden_vectors.rs` with the
// PRODUCTION Argon2 profile — if any of these fail, the phone cannot decrypt real vaults, so a
// failure here is always a real bug, never a test to loosen.

import XCTest
@testable import NorthKey

private struct Golden: Decodable {
    struct Item: Decodable {
        let id: String
        let password: String
        let title: String
        let username: String
    }
    let items: [Item]
    let password: String
    let vault_blob_b64: String
    let vault_key_b64: String
    let vault_version: UInt64
    let wrapped_key_b64: String
}

final class VaultCryptoTests: XCTestCase {
    private func golden() throws -> Golden {
        let url = try XCTUnwrap(
            Bundle(for: VaultCryptoTests.self).url(forResource: "golden-vault", withExtension: "json"),
            "golden-vault.json missing from the test bundle — check project.yml resources")
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    /// HChaCha20 vector computed by the Rust `chacha20` crate the desktop uses.
    func testHChaCha20MatchesRustVector() throws {
        let key = Data((0...31).map { UInt8($0) })
        let nonce = try XCTUnwrap(Data(hexString: "000000090000004a0000000031415927"))
        let out = VaultCrypto.hchacha20(key: key, nonce16: nonce)
        XCTAssertEqual(
            out.hexString,
            "82413b4227b27bfed30e42508a877d73a0f9e4d58a74a853c12ec41326d3ecdc")
    }

    /// Argon2id (production params) + SNTL unwrap: master password → exact vault key.
    func testUnwrapGoldenWrappedKey() throws {
        let g = try golden()
        let blob = try XCTUnwrap(Data(base64Encoded: g.wrapped_key_b64))
        let vk = try VaultCrypto.unwrapPasswordBlob(blob, password: g.password)
        XCTAssertEqual(vk.base64EncodedString(), g.vault_key_b64)
    }

    func testWrongPasswordThrows() throws {
        let g = try golden()
        let blob = try XCTUnwrap(Data(base64Encoded: g.wrapped_key_b64))
        XCTAssertThrowsError(try VaultCrypto.unwrapPasswordBlob(blob, password: "not-the-password")) {
            guard case VaultCryptoError.wrongPassword = $0 else {
                return XCTFail("expected wrongPassword, got \($0)")
            }
        }
    }

    /// SVLT decode + zstd + item envelopes: the exact blob a desktop pushed decodes to its items.
    func testDecodeGoldenVaultBlob() throws {
        let g = try golden()
        let vk = try XCTUnwrap(Data(base64Encoded: g.vault_key_b64))
        let blob = try XCTUnwrap(Data(base64Encoded: g.vault_blob_b64))
        let doc = try VaultCrypto.decodeSyncBlob(vaultKey: vk, blob: blob, version: g.vault_version)
        XCTAssertEqual(doc.items.count, g.items.count)

        var opened: [String: VaultItem] = [:]
        for b64 in doc.items {
            let env = try XCTUnwrap(Data(base64Encoded: b64))
            let item = try VaultCrypto.openItem(vaultKey: vk, envelope: env)
            opened[item.id] = item
        }
        for expected in g.items {
            let item = try XCTUnwrap(opened[expected.id], "item \(expected.id) missing")
            XCTAssertEqual(item.title, expected.title)
            XCTAssertEqual(item.login?.username, expected.username)
            XCTAssertEqual(item.login?.password, expected.password)
        }
    }

    /// Decoding with the wrong version must fail — the version is authenticated (AAD), which is
    /// what stops a server from silently rolling a vault back.
    func testVersionIsAuthenticated() throws {
        let g = try golden()
        let vk = try XCTUnwrap(Data(base64Encoded: g.vault_key_b64))
        let blob = try XCTUnwrap(Data(base64Encoded: g.vault_blob_b64))
        XCTAssertThrowsError(
            try VaultCrypto.decodeSyncBlob(vaultKey: vk, blob: blob, version: g.vault_version + 1))
    }

    /// What the phone seals, the phone (and byte-format-wise, the desktop) can open again.
    func testSealAndEncodeRoundTrip() throws {
        let vk = Data(repeating: 0x42, count: 32)
        var item = VaultItem.newLogin(title: "Round Trip", now: 1_700_000_000)
        item.login = VaultLogin(username: "user@example.com", password: "pw-123", totp: nil)
        item.urls = [VaultUrlMatch(url: "example.com", mode: "domain")]
        item.notes = "hello"

        let env = try VaultCrypto.sealItem(vaultKey: vk, item: item)
        let reopened = try VaultCrypto.openItem(vaultKey: vk, envelope: env)
        XCTAssertEqual(reopened.id, item.id)
        XCTAssertEqual(reopened.title, "Round Trip")
        XCTAssertEqual(reopened.login?.username, "user@example.com")
        XCTAssertEqual(reopened.login?.password, "pw-123")
        XCTAssertEqual(reopened.urls.first?.url, "example.com")
        XCTAssertEqual(reopened.notes, "hello")

        let doc = VaultDocument(
            format: 1, items: [env.base64EncodedString()],
            tombstones: [[.id("dead-beef"), .ts(1_700_000_001)]])
        let blob = try VaultCrypto.encodeSyncBlob(vaultKey: vk, document: doc, version: 7)
        let decoded = try VaultCrypto.decodeSyncBlob(vaultKey: vk, blob: blob, version: 7)
        XCTAssertEqual(decoded.items, doc.items)
        XCTAssertEqual(decoded.tombstones.count, 1)
        if case .id(let s) = decoded.tombstones[0][0] { XCTAssertEqual(s, "dead-beef") } else {
            XCTFail("tombstone[0][0] should be the id")
        }
        if case .ts(let t) = decoded.tombstones[0][1] { XCTAssertEqual(t, 1_700_000_001) } else {
            XCTFail("tombstone[0][1] should be the timestamp")
        }
    }

    /// The item JSON the phone writes must use the Rust field names (custom_fields, created_at…).
    func testItemJsonFieldNamesMatchSerde() throws {
        var item = VaultItem.newLogin(title: "T", now: 5)
        item.customFields = [VaultCustomField(name: "pin", value: "1234", secret: true)]
        let json = try JSONSerialization.jsonObject(with: JSONEncoder().encode(item)) as? [String: Any]
        let obj = try XCTUnwrap(json)
        XCTAssertNotNil(obj["created_at"])
        XCTAssertNotNil(obj["updated_at"])
        XCTAssertNotNil(obj["password_changed_at"])
        XCTAssertNotNil(obj["custom_fields"])
        XCTAssertEqual(obj["type"] as? String, "login")
        XCTAssertNil(obj["createdAt"], "camelCase field names would be unreadable by the desktop")
    }

    func testBase32AndOtpauthParsing() {
        // RFC 4648 test vector: BASE32("foobar") = "MZXW6YTBOI======".
        XCTAssertEqual(
            TotpParse.base32Decode("MZXW6YTBOI======"), Data("foobar".utf8))
        let entry = TotpParse.entry(
            from: "otpauth://totp/NorthKey:me?secret=MZXW6YTBOI&issuer=NorthKey&algorithm=SHA1&digits=6&period=30",
            title: "t")
        XCTAssertEqual(entry?.secret, Data("foobar".utf8))
        XCTAssertEqual(entry?.digits, 6)
        XCTAssertEqual(entry?.period, 30)
        // Bare base32 secrets work too (that's what the desktop stores from most imports).
        XCTAssertNotNil(TotpParse.entry(from: "MZXW6YTBOI", title: "t"))
    }
}

private extension Data {
    init?(hexString: String) {
        guard hexString.count % 2 == 0 else { return nil }
        var out = Data(capacity: hexString.count / 2)
        var idx = hexString.startIndex
        while idx < hexString.endIndex {
            let next = hexString.index(idx, offsetBy: 2)
            guard let b = UInt8(hexString[idx..<next], radix: 16) else { return nil }
            out.append(b)
            idx = next
        }
        self = out
    }

    var hexString: String { map { String(format: "%02x", $0) }.joined() }
}
