// The phone's vault crypto — byte-compatible with the Rust core, verified by the committed
// golden vectors in NorthKeyTests/Fixtures/golden-vault.json (generated by
// crates/core/tests/ios_golden_vectors.rs).
//
// Building blocks:
//   - Argon2id (m=64MiB, t=3, p=4) via the vendored reference C implementation
//     (Vendor/argon2, compiled with ARGON2_NO_THREADS — output verified byte-identical to the
//     desktop's Rust `argon2` crate at these parameters).
//   - XChaCha20-Poly1305 = HChaCha20 subkey (implemented below, vector-tested) + CryptoKit's
//     IETF ChaChaPoly with a 4-zero-byte + 8-byte nonce — the exact construction the Rust
//     `chacha20poly1305` crate uses.
//   - HKDF-SHA256 via CryptoKit, with the same `sentinel/v1/*` info strings as the Rust core
//     (protocol constants — never rebrand them).
//   - zstd via the vendored C library (streaming decompress: Rust's encoder doesn't always
//     record the content size in the frame header).
//
// Formats mirrored 1:1 from the Rust core:
//   wrapped key (SNTL):  "SNTL" | ver=1 | wrapper_type | params_len u16 LE | salt16 | nonce24 | ct48
//   sync blob   (SVLT):  "SVLT" | ver=1 | 0 0 0 | nonce24 | ct        AAD = header ‖ version u64 LE
//   item envelope:       ver=1 | item_id16 | updated_at i64 LE | nonce24 | ct   AAD = first 25 bytes

import CryptoKit
import Foundation
import Security

enum VaultCryptoError: Error, LocalizedError {
    case badFormat(String)
    case decryptFailed
    case wrongPassword
    case zstd(String)

    var errorDescription: String? {
        switch self {
        case .badFormat(let what): return "Unexpected data format (\(what))."
        case .decryptFailed: return "Decryption failed — wrong key or corrupted data."
        case .wrongPassword: return "Wrong master password."
        case .zstd(let m): return "Compression error: \(m)"
        }
    }
}

enum VaultCrypto {
    // MARK: - HChaCha20 (subkey derivation for XChaCha20-Poly1305)

    /// One ChaCha20 block permutation over key ‖ 16-byte nonce, returning words 0–3 and 12–15.
    /// Unit-tested against a vector computed by the Rust `chacha20` crate the desktop uses.
    static func hchacha20(key: Data, nonce16: Data) -> Data {
        precondition(key.count == 32 && nonce16.count == 16)
        func le32(_ d: Data, _ i: Int) -> UInt32 {
            let b = [UInt8](d)
            return UInt32(b[i]) | UInt32(b[i + 1]) << 8 | UInt32(b[i + 2]) << 16 | UInt32(b[i + 3]) << 24
        }
        var s = [UInt32](repeating: 0, count: 16)
        s[0] = 0x6170_7865; s[1] = 0x3320_646e; s[2] = 0x7962_2d32; s[3] = 0x6b20_6574
        for i in 0..<8 { s[4 + i] = le32(key, i * 4) }
        for i in 0..<4 { s[12 + i] = le32(nonce16, i * 4) }

        func rotl(_ v: UInt32, _ n: UInt32) -> UInt32 { (v << n) | (v >> (32 - n)) }
        func quarter(_ a: Int, _ b: Int, _ c: Int, _ d: Int) {
            s[a] = s[a] &+ s[b]; s[d] = rotl(s[d] ^ s[a], 16)
            s[c] = s[c] &+ s[d]; s[b] = rotl(s[b] ^ s[c], 12)
            s[a] = s[a] &+ s[b]; s[d] = rotl(s[d] ^ s[a], 8)
            s[c] = s[c] &+ s[d]; s[b] = rotl(s[b] ^ s[c], 7)
        }
        for _ in 0..<10 {
            quarter(0, 4, 8, 12); quarter(1, 5, 9, 13); quarter(2, 6, 10, 14); quarter(3, 7, 11, 15)
            quarter(0, 5, 10, 15); quarter(1, 6, 11, 12); quarter(2, 7, 8, 13); quarter(3, 4, 9, 14)
        }
        var out = Data(capacity: 32)
        for i in [0, 1, 2, 3, 12, 13, 14, 15] {
            var w = s[i].littleEndian
            withUnsafeBytes(of: &w) { out.append(contentsOf: $0) }
        }
        return out
    }

    // MARK: - XChaCha20-Poly1305 (24-byte nonce), matching the Rust crate's construction

    static func xchachaOpen(key: Data, nonce24: Data, ciphertext: Data, aad: Data) throws -> Data {
        precondition(key.count == 32 && nonce24.count == 24)
        let subkey = hchacha20(key: key, nonce16: nonce24.prefix(16))
        var ietfNonce = Data(repeating: 0, count: 4)
        ietfNonce.append(nonce24.suffix(8))
        guard ciphertext.count >= 16 else { throw VaultCryptoError.badFormat("ciphertext too short") }
        let ct = ciphertext.prefix(ciphertext.count - 16)
        let tag = ciphertext.suffix(16)
        do {
            let box = try ChaChaPoly.SealedBox(
                nonce: ChaChaPoly.Nonce(data: ietfNonce), ciphertext: ct, tag: tag)
            return try ChaChaPoly.open(box, using: SymmetricKey(data: subkey), authenticating: aad)
        } catch {
            throw VaultCryptoError.decryptFailed
        }
    }

    static func xchachaSeal(key: Data, plaintext: Data, aad: Data) throws -> (nonce24: Data, ciphertext: Data) {
        var nonce24 = Data(count: 24)
        _ = nonce24.withUnsafeMutableBytes { SecRandomCopyBytes(kSecRandomDefault, 24, $0.baseAddress!) }
        let subkey = hchacha20(key: key, nonce16: nonce24.prefix(16))
        var ietfNonce = Data(repeating: 0, count: 4)
        ietfNonce.append(nonce24.suffix(8))
        let box = try ChaChaPoly.seal(
            plaintext, using: SymmetricKey(data: subkey),
            nonce: ChaChaPoly.Nonce(data: ietfNonce), authenticating: aad)
        return (nonce24, box.ciphertext + box.tag)
    }

    // MARK: - HKDF-SHA256 (info strings are protocol constants shared with Rust)

    static let infoVaultOuter = "sentinel/v1/vault/outer"
    static let infoVaultItem = "sentinel/v1/vault/item"
    static let infoAuthLogin = "sentinel/v1/auth/login"
    static let infoFileBlob = "sentinel/v1/file/blob"

    static func hkdf32(ikm: Data, salt: Data?, info: String) -> Data {
        let key = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: SymmetricKey(data: ikm),
            salt: salt ?? Data(),
            info: Data(info.utf8),
            outputByteCount: 32)
        return key.withUnsafeBytes { Data($0) }
    }

    // MARK: - Argon2id (vendored reference C; production profile — the only profile real blobs use)

    static func argon2idKek(password: String, salt: Data) throws -> Data {
        precondition(salt.count == 16)
        var out = Data(count: 32)
        let pw = Data(password.utf8)
        let rc = out.withUnsafeMutableBytes { outB in
            pw.withUnsafeBytes { pwB in
                salt.withUnsafeBytes { saltB in
                    argon2id_hash_raw(
                        3, 65536, 4,
                        pwB.baseAddress, pw.count,
                        saltB.baseAddress, salt.count,
                        outB.baseAddress, 32)
                }
            }
        }
        guard rc == ARGON2_OK.rawValue else { throw VaultCryptoError.badFormat("argon2 rc \(rc)") }
        return out
    }

    // MARK: - Wrapped vault key (SNTL, wrapper_type 4 = master password)

    /// The 16-byte Argon2 salt embedded in a type-4 SNTL blob (same salt the sign-in proof uses,
    /// so one derivation covers login AND unwrap).
    static func passwordBlobSalt(_ blob: Data) throws -> Data {
        guard blob.count == 8 + 16 + 24 + 48,
              blob.prefix(4) == Data("SNTL".utf8),
              blob[4] == 1, blob[5] == 4,
              Int(blob[6]) | Int(blob[7]) << 8 == 16
        else { throw VaultCryptoError.badFormat("wrapped key") }
        return blob.subdata(in: 8..<24)
    }

    /// Unwrap the escrowed master-password blob to the 32-byte vault key.
    static func unwrapPasswordBlob(_ blob: Data, password: String) throws -> Data {
        let salt = try passwordBlobSalt(blob)
        let kek = try argon2idKek(password: password, salt: salt)
        return try unwrapPasswordBlob(blob, kek: kek)
    }

    /// Unwrap with an already-derived KEK (sign-in just derived it — no second Argon2 run).
    /// Falls back to `wrongPassword` on any AEAD failure, same as the password variant.
    static func unwrapPasswordBlob(_ blob: Data, kek: Data) throws -> Data {
        _ = try passwordBlobSalt(blob) // format check
        let header = blob.prefix(24) // magic..params = AAD
        let nonce = blob.subdata(in: 24..<48)
        let ct = blob.subdata(in: 48..<blob.count)
        do {
            let vk = try xchachaOpen(key: kek, nonce24: nonce, ciphertext: ct, aad: Data(header))
            guard vk.count == 32 else { throw VaultCryptoError.badFormat("unwrapped key size") }
            return vk
        } catch {
            throw VaultCryptoError.wrongPassword
        }
    }

    /// Master-password sign-in proof: HKDF(KEK, "sentinel/v1/auth/login"). One-way — the server
    /// stores only its hash and can never recover the KEK that unwraps the vault key.
    static func loginProof(kek: Data) -> Data {
        hkdf32(ikm: kek, salt: nil, info: infoAuthLogin)
    }

    // MARK: - Sync blob (SVLT)

    static func decodeSyncBlob(vaultKey: Data, blob: Data, version: UInt64) throws -> VaultDocument {
        guard blob.count >= 8 + 24,
              blob.prefix(4) == Data("SVLT".utf8), blob[4] == 1
        else { throw VaultCryptoError.badFormat("sync blob") }
        let header = blob.prefix(8)
        let nonce = blob.subdata(in: 8..<32)
        let ct = blob.subdata(in: 32..<blob.count)
        var aad = Data(header)
        var v = version.littleEndian
        withUnsafeBytes(of: &v) { aad.append(contentsOf: $0) }
        let key = hkdf32(ikm: vaultKey, salt: nil, info: infoVaultOuter)
        let compressed = try xchachaOpen(key: key, nonce24: nonce, ciphertext: ct, aad: aad)
        let json = try Zstd.decompress(compressed)
        return try JSONDecoder().decode(VaultDocument.self, from: json)
    }

    static func encodeSyncBlob(vaultKey: Data, document: VaultDocument, version: UInt64) throws -> Data {
        let json = try JSONEncoder().encode(document)
        let compressed = try Zstd.compress(json, level: 3)
        var header = Data("SVLT".utf8)
        header.append(contentsOf: [1, 0, 0, 0])
        var aad = header
        var v = version.littleEndian
        withUnsafeBytes(of: &v) { aad.append(contentsOf: $0) }
        let key = hkdf32(ikm: vaultKey, salt: nil, info: infoVaultOuter)
        let (nonce, ct) = try xchachaSeal(key: key, plaintext: compressed, aad: aad)
        return header + nonce + ct
    }

    // MARK: - Item envelopes

    static func openItem(vaultKey: Data, envelope: Data) throws -> VaultItem {
        guard envelope.count >= 25 + 24 + 16, envelope[0] == 1 else {
            throw VaultCryptoError.badFormat("item envelope")
        }
        let idBytes = envelope.subdata(in: 1..<17)
        let header = envelope.prefix(25)
        let nonce = envelope.subdata(in: 25..<49)
        let ct = envelope.subdata(in: 49..<envelope.count)
        let key = hkdf32(ikm: vaultKey, salt: idBytes, info: infoVaultItem)
        let json = try xchachaOpen(key: key, nonce24: nonce, ciphertext: ct, aad: Data(header))
        return try JSONDecoder().decode(VaultItem.self, from: json)
    }

    static func sealItem(vaultKey: Data, item: VaultItem) throws -> Data {
        guard let uuid = UUID(uuidString: item.id) else {
            throw VaultCryptoError.badFormat("item id")
        }
        var idBytes = Data(count: 16)
        withUnsafeBytes(of: uuid.uuid) { idBytes = Data($0) }
        var header = Data([1])
        header.append(idBytes)
        var ts = item.updatedAt.littleEndian
        withUnsafeBytes(of: &ts) { header.append(contentsOf: $0) }
        let json = try JSONEncoder().encode(item)
        let key = hkdf32(ikm: vaultKey, salt: idBytes, info: infoVaultItem)
        let (nonce, ct) = try xchachaSeal(key: key, plaintext: json, aad: header)
        return header + nonce + ct
    }

    // MARK: - File transfer blob (SFIL) — matches crates/core/src/vault/fileblob.rs
    //   "SFIL" | ver=1 | 0 0 0 | salt16 | nonce24 | ct
    //   plaintext = meta_len(u32 LE) | meta_json | file_bytes, then zstd(3)
    //   AAD = header(8) ‖ salt(16);  key = HKDF(vault_key, salt, "sentinel/v1/file/blob")

    /// Filename + mime, sealed inside the blob (the server never sees them). Matches Rust `FileMeta`.
    struct FileMeta: Codable {
        var filename: String
        var mime: String
    }

    /// Open a received transfer blob into its metadata and raw file bytes.
    static func openFileBlob(vaultKey: Data, blob: Data) throws -> (meta: FileMeta, bytes: Data) {
        guard blob.count >= 8 + 16 + 24 + 16,
              blob.prefix(4) == Data("SFIL".utf8), blob[4] == 1
        else { throw VaultCryptoError.badFormat("file blob") }
        let header = blob.prefix(8)
        let salt = blob.subdata(in: 8..<24)
        let nonce = blob.subdata(in: 24..<48)
        let ct = blob.subdata(in: 48..<blob.count)
        var aad = Data(header)
        aad.append(salt)
        let key = hkdf32(ikm: vaultKey, salt: salt, info: infoFileBlob)
        let compressed = try xchachaOpen(key: key, nonce24: nonce, ciphertext: ct, aad: aad)
        let plaintext = try Zstd.decompress(compressed)
        guard plaintext.count >= 4 else { throw VaultCryptoError.badFormat("file plaintext") }
        let b = [UInt8](plaintext)
        let metaLen = Int(b[0]) | Int(b[1]) << 8 | Int(b[2]) << 16 | Int(b[3]) << 24
        guard metaLen >= 0, plaintext.count >= 4 + metaLen else {
            throw VaultCryptoError.badFormat("file meta length")
        }
        let metaJson = plaintext.subdata(in: 4..<(4 + metaLen))
        let fileBytes = plaintext.subdata(in: (4 + metaLen)..<plaintext.count)
        let meta = try JSONDecoder().decode(FileMeta.self, from: metaJson)
        return (meta, fileBytes)
    }

    // MARK: - File bundle (NKAR) — matches crates/core/src/vault/fileblob.rs
    //   "NKAR" | ver=1 | count(u32 LE) | [ name_len(u32 LE) | name_utf8 | data_len(u64 LE) | data ]*
    // A container so several files ride one transfer: it's the plaintext of an ordinary SFIL blob
    // whose FileMeta.mime is `bundleMime`. No crypto here — the SFIL seal provides confidentiality.

    /// Mime marking a sealed file whose bytes are a packed bundle of several files.
    static let bundleMime = "application/x-northkey-bundle"

    /// One file inside a bundle.
    struct BundleEntry: Equatable {
        var name: String
        var data: Data
    }

    /// Unpack a NKAR archive into its files, validating every length against the buffer.
    static func unpackBundle(_ bytes: Data) throws -> [BundleEntry] {
        let b = [UInt8](bytes)
        func u32(_ i: Int) -> Int {
            Int(b[i]) | Int(b[i + 1]) << 8 | Int(b[i + 2]) << 16 | Int(b[i + 3]) << 24
        }
        func u64(_ i: Int) -> Int {
            var v = 0
            for k in 0..<8 { v |= Int(b[i + k]) << (8 * k) }
            return v
        }
        guard b.count >= 9, Array(b[0..<4]) == Array("NKAR".utf8), b[4] == 1 else {
            throw VaultCryptoError.badFormat("file bundle")
        }
        let count = u32(5)
        var pos = 9
        var out: [BundleEntry] = []
        func fits(_ n: Int) -> Bool { pos >= 0 && n >= 0 && pos + n <= b.count }
        for _ in 0..<count {
            guard fits(4) else { throw VaultCryptoError.badFormat("file bundle") }
            let nlen = u32(pos); pos += 4
            guard fits(nlen), let name = String(bytes: b[pos..<pos + nlen], encoding: .utf8) else {
                throw VaultCryptoError.badFormat("file bundle")
            }
            pos += nlen
            guard fits(8) else { throw VaultCryptoError.badFormat("file bundle") }
            let dlen = u64(pos); pos += 8
            guard fits(dlen) else { throw VaultCryptoError.badFormat("file bundle") }
            out.append(BundleEntry(name: name, data: Data(b[pos..<pos + dlen])))
            pos += dlen
        }
        guard pos == b.count else { throw VaultCryptoError.badFormat("file bundle") }
        return out
    }

    /// Seal a file (name + mime + bytes) into a transfer blob for the user's other devices.
    static func sealFileBlob(vaultKey: Data, meta: FileMeta, bytes: Data) throws -> Data {
        var salt = Data(count: 16)
        _ = salt.withUnsafeMutableBytes { SecRandomCopyBytes(kSecRandomDefault, 16, $0.baseAddress!) }
        let metaJson = try JSONEncoder().encode(meta)
        var plaintext = Data()
        var len = UInt32(metaJson.count).littleEndian
        withUnsafeBytes(of: &len) { plaintext.append(contentsOf: $0) }
        plaintext.append(metaJson)
        plaintext.append(bytes)
        let compressed = try Zstd.compress(plaintext, level: 3)

        var header = Data("SFIL".utf8)
        header.append(contentsOf: [1, 0, 0, 0])
        var aad = header
        aad.append(salt)
        let key = hkdf32(ikm: vaultKey, salt: salt, info: infoFileBlob)
        let (nonce, ct) = try xchachaSeal(key: key, plaintext: compressed, aad: aad)
        return header + salt + nonce + ct
    }
}

// MARK: - zstd bridge (vendored C)

enum Zstd {
    static func compress(_ data: Data, level: Int32) throws -> Data {
        let bound = ZSTD_compressBound(data.count)
        var out = Data(count: bound)
        let written = out.withUnsafeMutableBytes { outB in
            data.withUnsafeBytes { inB in
                ZSTD_compress(outB.baseAddress, bound, inB.baseAddress, data.count, level)
            }
        }
        guard ZSTD_isError(written) == 0 else {
            throw VaultCryptoError.zstd(String(cString: ZSTD_getErrorName(written)))
        }
        out.removeSubrange(written..<out.count)
        return out
    }

    /// Streaming decompress — the Rust encoder doesn't always record the frame content size.
    static func decompress(_ data: Data) throws -> Data {
        guard let stream = ZSTD_createDStream() else { throw VaultCryptoError.zstd("createDStream") }
        defer { ZSTD_freeDStream(stream) }
        var out = Data()
        let chunkSize = ZSTD_DStreamOutSize()
        var chunk = [UInt8](repeating: 0, count: chunkSize)
        try data.withUnsafeBytes { (inB: UnsafeRawBufferPointer) in
            var input = ZSTD_inBuffer(src: inB.baseAddress, size: data.count, pos: 0)
            while input.pos < input.size {
                var progressed = false
                try chunk.withUnsafeMutableBytes { outB in
                    var output = ZSTD_outBuffer(dst: outB.baseAddress, size: chunkSize, pos: 0)
                    let rc = ZSTD_decompressStream(stream, &output, &input)
                    guard ZSTD_isError(rc) == 0 else {
                        throw VaultCryptoError.zstd(String(cString: ZSTD_getErrorName(rc)))
                    }
                    if output.pos > 0 {
                        out.append(contentsOf: outB.prefix(output.pos))
                        progressed = true
                    }
                    if rc == 0 && input.pos >= input.size { progressed = true }
                }
                if !progressed && input.pos >= input.size { break }
            }
        }
        return out
    }
}
